{
 "title": "Redis Metrics",
 "tags": [ "redis" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Connected Clients",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "datasourceUid": "P4169E866C3094E38", "expr": "redis_connected_clients" }
   ]
  },
  {
   "title": "Used Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "datasourceUid": "P4169E866C3094E38", "expr": "redis_used_memory" }
   ]
  },
  {
   "title": "Commands Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "datasourceUid": "P4169E866C3094E38",
     "expr": "rate(redis_commands_processed_total[5m])",
     "legendFormat": "Total Commands"
    }
   ]
  },
  {
   "title": "Keys per Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "datasourceUid": "P4169E866C3094E38", "expr": "redis_db_keys", "legendFormat": "Keys in DB {{db}}" }
   ]
  },
  {
   "title": "Command Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "datasourceUid": "P4169E866C3094E38",
     "expr": "rate(redis_commands_duration_seconds_total[5m]) * 1000",
     "legendFormat": "Avg Latency"
    }
   ]
  }
 ]
}